# Generated by Django 6.0 on 2025-12-06 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата и время'),
        ),
        migrations.AlterField(
            model_name='review',
            name='hero1_rating',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=1, verbose_name='Оценка героя 1'),
        ),
        migrations.AlterField(
            model_name='review',
            name='hero2_rating',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=1, verbose_name='Оценка героя 2'),
        ),
        migrations.AlterField(
            model_name='review',
            name='hero3_rating',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=1, verbose_name='Оценка героя 3'),
        ),
        migrations.AlterField(
            model_name='review',
            name='hero4_rating',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=1, verbose_name='Оценка героя 4'),
        ),
        migrations.AlterField(
            model_name='review',
            name='hero5_rating',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=1, verbose_name='Оценка героя 5'),
        ),
        migrations.AlterField(
            model_name='review',
            name='overall_rating',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=1, verbose_name='Общая оценка'),
        ),
    ]
