# Generated by Django 6.0 on 2025-12-07 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_review_created_at_alter_review_hero1_rating_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'verbose_name': 'Отзыв', 'verbose_name_plural': 'Отзывы'},
        ),
        migrations.AlterField(
            model_name='review',
            name='hero1_rating',
            field=models.IntegerField(choices=[(0, '-'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=0, verbose_name='Оценка героя 1'),
        ),
        migrations.AlterField(
            model_name='review',
            name='hero2_rating',
            field=models.IntegerField(choices=[(0, '-'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=0, verbose_name='Оценка героя 2'),
        ),
        migrations.AlterField(
            model_name='review',
            name='hero3_rating',
            field=models.IntegerField(choices=[(0, '-'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=0, verbose_name='Оценка героя 3'),
        ),
        migrations.AlterField(
            model_name='review',
            name='hero4_rating',
            field=models.IntegerField(choices=[(0, '-'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=0, verbose_name='Оценка героя 4'),
        ),
        migrations.AlterField(
            model_name='review',
            name='hero5_rating',
            field=models.IntegerField(choices=[(0, '-'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=0, verbose_name='Оценка героя 5'),
        ),
    ]
