# Generated by Django 6.0 on 2025-12-07 18:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_review_options_alter_review_hero1_rating_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('aka', models.CharField(blank=True, max_length=100, verbose_name='Прозвище')),
                ('race', models.CharField(choices=[('human', 'Человек'), ('elf', 'Эльф'), ('dwarf', 'Гном'), ('orc', 'Орк'), ('halfling', 'Хоббит'), ('other', 'Другое')], default='human', max_length=20, verbose_name='Раса')),
                ('gender', models.CharField(choices=[('male', 'Мужской'), ('female', 'Женский'), ('other', 'Другое')], default='male', max_length=10, verbose_name='Пол')),
                ('age', models.IntegerField(blank=True, null=True, verbose_name='Возраст')),
                ('height', models.IntegerField(blank=True, null=True, verbose_name='Рост (см)')),
                ('birth_place', models.CharField(max_length=100, verbose_name='Место рождения')),
                ('phone', models.CharField(max_length=20, verbose_name='Номер телефона')),
                ('biography', models.TextField(verbose_name='Биография')),
                ('convicted_for', models.TextField(blank=True, verbose_name='Осуждён за')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='hero_photos/', verbose_name='Фото')),
                ('is_active', models.BooleanField(default=True, verbose_name='Действующий герой')),
                ('position', models.IntegerField(blank=True, help_text='Позиция от 1 до 5 для отображения в форме отзыва', null=True, unique=True, verbose_name='Позиция в списке (1-5)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Герой',
                'verbose_name_plural': 'Герои',
                'ordering': ['position'],
            },
        ),
        migrations.AddField(
            model_name='review',
            name='hero1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hero1_reviews', to='main.hero', verbose_name='Герой 1'),
        ),
        migrations.AddField(
            model_name='review',
            name='hero2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hero2_reviews', to='main.hero', verbose_name='Герой 2'),
        ),
        migrations.AddField(
            model_name='review',
            name='hero3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hero3_reviews', to='main.hero', verbose_name='Герой 3'),
        ),
        migrations.AddField(
            model_name='review',
            name='hero4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hero4_reviews', to='main.hero', verbose_name='Герой 4'),
        ),
        migrations.AddField(
            model_name='review',
            name='hero5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hero5_reviews', to='main.hero', verbose_name='Герой 5'),
        ),
    ]
