# Generated by Django 6.0 on 2025-12-07 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_hero_review_hero1_review_hero2_review_hero3_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hero',
            name='race',
            field=models.CharField(max_length=100, verbose_name='Раса'),
        ),
    ]
