# Generated by Django 6.0 on 2025-12-09 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_hero_race'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='person_photos/', verbose_name='Фото')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('age', models.IntegerField(verbose_name='Возраст')),
                ('city', models.CharField(choices=[('city1', 'Город 1'), ('city2', 'Город 2'), ('city3', 'Город 3'), ('city4', 'Город 4'), ('city5', 'Город 5')], max_length=50, verbose_name='Город')),
                ('comment', models.TextField(verbose_name='Комментарий')),
                ('features', models.TextField(blank=True, verbose_name='Приметы')),
                ('clothing', models.TextField(blank=True, verbose_name='Одежда')),
                ('status', models.CharField(choices=[('missing', 'Пропал'), ('wanted', 'Розыск'), ('found', 'Найден'), ('caught', 'Пойман')], max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Человек',
                'verbose_name_plural': 'Люди',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='hero',
            name='gender',
            field=models.CharField(choices=[('male', 'мужской'), ('female', 'женский'), ('other', 'другое')], default='male', max_length=10, verbose_name='Пол'),
        ),
    ]
