# Generated by Django 6.0 on 2025-12-20 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_person_alter_hero_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hero',
            name='is_active',
        ),
        migrations.AddField(
            model_name='hero',
            name='status',
            field=models.CharField(choices=[('active', 'Действующий герой'), ('dispatch', 'Диспетчер'), ('retired', 'В отставке')], default='active', max_length=20, verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='hero',
            name='superpower',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Суперспособность'),
        ),
        migrations.AddField(
            model_name='hero',
            name='superpower_description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание суперспособности'),
        ),
        migrations.AlterField(
            model_name='person',
            name='city',
            field=models.CharField(choices=[('city1', 'Вуменсфилд'), ('city2', 'Девоур Сан'), ('city3', 'Джымиетта'), ('city4', 'Занисасаллэ'), ('city5', 'Ивклитор'), ('city6', 'Кант'), ('city7', 'Клеверленд'), ('city8', 'Ксения'), ('city9', 'Марина'), ('city10', 'Мидалтавн'), ('city11', 'Похфимар'), ('city12', 'Ротик'), ('city13', 'С. Перм'), ('city14', 'Садженск'), ('city15', 'Симпсоны'), ('city16', 'Синабоны'), ('city17', 'Сыендуски'), ('city18', 'Тимчиккотик'), ('city19', 'Толетоле'), ('city20', 'Томаш'), ('city21', 'Фараон'), ('city22', 'Финн'), ('city23', 'Янго')], max_length=50, verbose_name='Город'),
        ),
    ]
