# Generated by Django 6.0 on 2026-04-22 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_hero_is_active_hero_status_hero_superpower_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hero',
            name='birth_place',
            field=models.CharField(choices=[('city1', 'Вуменсфилд'), ('city2', 'Девоур Сан'), ('city3', 'Джымиетта'), ('city4', 'Занисасаллэ'), ('city5', 'Ивклитор'), ('city6', 'Кант'), ('city7', 'Клеверленд'), ('city8', 'Ксения'), ('city9', 'Марина'), ('city10', 'Мидалтавн'), ('city11', 'Похфимар'), ('city12', 'Ротик'), ('city13', 'С. Перм'), ('city14', 'Садженск'), ('city15', 'Симпсоны'), ('city16', 'Синабоны'), ('city17', 'Сыендуски'), ('city18', 'Тимчиккотик'), ('city19', 'Толетоле'), ('city20', 'Томаш'), ('city21', 'Фараон'), ('city22', 'Финн'), ('city23', 'Янго')], max_length=50, verbose_name='Место рождения'),
        ),
        migrations.AlterField(
            model_name='hero',
            name='gender',
            field=models.CharField(choices=[('male', 'мужской'), ('female', 'женский'), ('other', 'другой')], default='male', max_length=10, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='hero',
            name='status',
            field=models.CharField(choices=[('active', 'Действующий герой'), ('retired', 'В отставке'), ('dispatch', 'Диспетчер'), ('staff', 'Персонал'), ('staff_retired', 'Персонал в отставке')], default='active', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='person',
            name='city',
            field=models.CharField(choices=[('city1', 'Вуменсфилд'), ('city2', 'Девоур Сан'), ('city3', 'Джымиетта'), ('city4', 'Занисасаллэ'), ('city5', 'Ивклитор'), ('city6', 'Кант'), ('city7', 'Клеверленд'), ('city8', 'Ксениа'), ('city9', 'Марина'), ('city10', 'Мидалтавн'), ('city11', 'Похфимар'), ('city12', 'Ротик'), ('city13', 'С. Перм'), ('city14', 'Садженск'), ('city15', 'Симпсоны'), ('city16', 'Синабоны'), ('city17', 'Сыендуски'), ('city18', 'Тимчиккотик'), ('city19', 'Толетоле'), ('city20', 'Томаш'), ('city21', 'Фараон'), ('city22', 'Финн'), ('city23', 'Янго'), ('city24', 'Батикант')], max_length=50, verbose_name='Город'),
        ),
    ]
