# Generated by Django 6.0 on 2026-04-22 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_hero_birth_place_alter_hero_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hero',
            name='position_text',
            field=models.TextField(blank=True, null=True, verbose_name='Должность'),
        ),
    ]
